version: "3"
services:
  strongswan-ikev2_1:
    build: .
    container_name: strongswan-ikev2_1
    cap_add:
      - NET_ADMIN
    #user: root
    ports:
      - 500/udp:500/udp
      - 4500/udp:4500/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.eth0.proxy_ndp=1
    restart: always
