version: "3"
services:
  ikev2-vpn-server:
    build: .
    container_name: vpn-server
    image: gaomd/ikev2-vpn-server
    cap_add:
      - NET_ADMIN
    #user: root
    ports:
      - 500/udp
      - 4500/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.eth0.proxy_ndp=1
    restart: always
